require('dotenv').config();
const express=require('express'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),multer=require('multer'),path=require('path'),cors=require('cors'),compression=require('compression'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),fs=require('fs');
const app=express();
app.use(compression());app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));app.use(cors());app.use(express.json({limit:'50mb'}));app.use(express.urlencoded({extended:true,limit:'50mb'}));app.use(express.static('public'));app.use('/uploads',express.static('uploads'));
app.use('/api/',rateLimit({windowMs:15*60*1000,max:300}));
if(!fs.existsSync('uploads'))fs.mkdirSync('uploads');
const storage=multer.diskStorage({destination:(r,f,cb)=>cb(null,'uploads/'),filename:(r,f,cb)=>cb(null,Date.now()+'-'+Math.round(Math.random()*1E9)+path.extname(f.originalname))});
const upload=multer({storage,limits:{fileSize:10*1024*1024},fileFilter:(r,f,cb)=>{const t=/jpeg|jpg|png|gif|webp|svg/;cb(null,t.test(path.extname(f.originalname).toLowerCase())&&t.test(f.mimetype))}});

const userSchema=new mongoose.Schema({username:{type:String,required:true,unique:true,trim:true},email:{type:String,required:true,unique:true,lowercase:true},password:{type:String,required:true},avatar:{type:String,default:''},bio:{type:String,default:'',maxlength:200},role:{type:String,enum:['user','admin'],default:'user'},followersCount:{type:Number,default:0},followingCount:{type:Number,default:0},templatesCount:{type:Number,default:0},totalTemplateLikes:{type:Number,default:0},totalTemplateUses:{type:Number,default:0},canShowAds:{type:Boolean,default:false},adRevenue:{type:Number,default:0},createdAt:{type:Date,default:Date.now}});
const User=mongoose.model('User',userSchema);

const templateSchema=new mongoose.Schema({name:{type:String,required:true},description:{type:String,default:''},category:{type:String,enum:['简约','科技','文艺','商务','时尚','教育','美食','旅行','节日','自定义'],default:'自定义'},htmlContent:{type:String,required:true},cssContent:{type:String,default:''},author:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true},isBuiltin:{type:Boolean,default:false},isPublic:{type:Boolean,default:true},likes:{type:Number,default:0},usageCount:{type:Number,default:0},tags:[String],likedBy:[{type:mongoose.Schema.Types.ObjectId,ref:'User'}],adSlots:[{position:String,enabled:Boolean}],createdAt:{type:Date,default:Date.now},updatedAt:{type:Date,default:Date.now}});
templateSchema.index({name:'text',description:'text',tags:'text'});
const Template=mongoose.model('Template',templateSchema);

const followSchema=new mongoose.Schema({follower:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true},following:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true},createdAt:{type:Date,default:Date.now}});
followSchema.index({follower:1,following:1},{unique:true});
const Follow=mongoose.model('Follow',followSchema);

const auth=(req,res,next)=>{try{const t=req.header('Authorization')?.replace('Bearer ','');if(!t)return res.status(401).json({error:'请先登录'});req.userId=jwt.verify(t,process.env.JWT_SECRET).userId;next()}catch(e){res.status(401).json({error:'登录已过期'})}};
const optAuth=(req,res,next)=>{try{const t=req.header('Authorization')?.replace('Bearer ','');if(t)req.userId=jwt.verify(t,process.env.JWT_SECRET).userId}catch(e){}next()};

app.post('/api/auth/register',async(req,res)=>{try{const{username,email,password}=req.body;if(!username||!email||!password)return res.status(400).json({error:'请填写所有字段'});if(password.length<6)return res.status(400).json({error:'密码至少6位'});const exists=await User.findOne({$or:[{email},{username}]});if(exists)return res.status(400).json({error:'用户名或邮箱已存在'});const user=new User({username,email,password:await bcrypt.hash(password,12)});await user.save();const token=jwt.sign({userId:user._id},process.env.JWT_SECRET,{expiresIn:'30d'});res.status(201).json({token,user:{id:user._id,username:user.username,email:user.email,bio:'',followersCount:0,followingCount:0,templatesCount:0,canShowAds:false,adRevenue:0}})}catch(e){res.status(500).json({error:'注册失败：'+e.message})}});

app.post('/api/auth/login',async(req,res)=>{try{const{email,password}=req.body;const user=await User.findOne({email});if(!user||!(await bcrypt.compare(password,user.password)))return res.status(400).json({error:'邮箱或密码错误'});const token=jwt.sign({userId:user._id},process.env.JWT_SECRET,{expiresIn:'30d'});res.json({token,user:{id:user._id,username:user.username,email:user.email,bio:user.bio,followersCount:user.followersCount,followingCount:user.followingCount,templatesCount:user.templatesCount,canShowAds:user.canShowAds,adRevenue:user.adRevenue,role:user.role}})}catch(e){res.status(500).json({error:'登录失败'})}});

app.get('/api/auth/me',auth,async(req,res)=>{try{const user=await User.findById(req.userId).select('-password');if(!user)return res.status(404).json({error:'用户不存在'});res.json({user})}catch(e){res.status(500).json({error:'获取失败'})}});

app.put('/api/auth/profile',auth,async(req,res)=>{try{const{username,bio}=req.body;const user=await User.findByIdAndUpdate(req.userId,{username,bio},{new:true}).select('-password');res.json({user})}catch(e){res.status(500).json({error:'更新失败'})}});

app.post('/api/upload',auth,upload.single('image'),(req,res)=>{if(!req.file)return res.status(400).json({error:'请选择图片'});res.json({url:'/uploads/'+req.file.filename})});

app.post('/api/templates',auth,async(req,res)=>{try{const{name,description,category,htmlContent,cssContent,isPublic,tags}=req.body;if(!name||!htmlContent)return res.status(400).json({error:'名称和内容不能为空'});const template=new Template({name,description,category:category||'自定义',htmlContent,cssContent:cssContent||'',author:req.userId,isPublic:isPublic!==false,tags:tags||[]});await template.save();await User.findByIdAndUpdate(req.userId,{$inc:{templatesCount:1}});const populated=await Template.findById(template._id).populate('author','username avatar');res.status(201).json({template:populated})}catch(e){res.status(500).json({error:'创建失败：'+e.message})}});

app.get('/api/templates',optAuth,async(req,res)=>{try{const{category,sort,search,page=1,limit=20,mine}=req.query;const query={};if(mine==='true'&&req.userId){query.author=req.userId}else{query.isPublic=true}if(category&&category!=='全部')query.category=category;if(search)query.$text={$search:search};let sortObj={createdAt:-1};if(sort==='popular')sortObj={likes:-1};if(sort==='most-used')sortObj={usageCount:-1};const total=await Template.countDocuments(query);const templates=await Template.find(query).populate('author','username avatar followersCount').sort(sortObj).skip((page-1)*limit).limit(parseInt(limit));res.json({templates,total,page:parseInt(page),pages:Math.ceil(total/limit)})}catch(e){res.status(500).json({error:'获取失败'})}});

app.get('/api/templates/builtin',async(req,res)=>{try{const templates=await Template.find({isBuiltin:true}).populate('author','username avatar');res.json({templates})}catch(e){res.status(500).json({error:'获取失败'})}});

app.get('/api/templates/:id',optAuth,async(req,res)=>{try{const template=await Template.findById(req.params.id).populate('author','username avatar bio followersCount');if(!template)return res.status(404).json({error:'模板不存在'});let isLiked=false,isFollowing=false;if(req.userId){isLiked=template.likedBy.includes(req.userId);if(template.author._id.toString()!==req.userId){isFollowing=!!(await Follow.findOne({follower:req.userId,following:template.author._id}))}}res.json({template,isLiked,isFollowing})}catch(e){res.status(500).json({error:'获取失败'})}});

app.delete('/api/templates/:id',auth,async(req,res)=>{try{const template=await Template.findById(req.params.id);if(!template)return res.status(404).json({error:'模板不存在'});if(template.author.toString()!==req.userId)return res.status(403).json({error:'无权限'});await Template.findByIdAndDelete(req.params.id);await User.findByIdAndUpdate(req.userId,{$inc:{templatesCount:-1}});res.json({message:'删除成功'})}catch(e){res.status(500).json({error:'删除失败'})}});

app.post('/api/templates/:id/like',auth,async(req,res)=>{try{const template=await Template.findById(req.params.id);if(!template)return res.status(404).json({error:'模板不存在'});const i=template.likedBy.indexOf(req.userId);if(i>-1){template.likedBy.splice(i,1);template.likes=Math.max(0,template.likes-1);await User.findByIdAndUpdate(template.author,{$inc:{totalTemplateLikes:-1}})}else{template.likedBy.push(req.userId);template.likes+=1;await User.findByIdAndUpdate(template.author,{$inc:{totalTemplateLikes:1}})}await template.save();res.json({likes:template.likes,isLiked:i===-1})}catch(e){res.status(500).json({error:'操作失败'})}});

app.post('/api/templates/:id/use',auth,async(req,res)=>{try{await Template.findByIdAndUpdate(req.params.id,{$inc:{usageCount:1}});const t=await Template.findById(req.params.id);if(t)await User.findByIdAndUpdate(t.author,{$inc:{totalTemplateUses:1}});res.json({message:'ok'})}catch(e){res.status(500).json({error:'操作失败'})}});

app.post('/api/users/:id/follow',auth,async(req,res)=>{try{if(req.params.id===req.userId)return res.status(400).json({error:'不能关注自己'});const existing=await Follow.findOne({follower:req.userId,following:req.params.id});if(existing){await Follow.findByIdAndDelete(existing._id);await User.findByIdAndUpdate(req.params.id,{$inc:{followersCount:-1}});await User.findByIdAndUpdate(req.userId,{$inc:{followingCount:-1}});const u=await User.findById(req.params.id);if(u&&u.followersCount<parseInt(process.env.AD_FOLLOWER_THRESHOLD||1000))await User.findByIdAndUpdate(req.params.id,{canShowAds:false});res.json({isFollowing:false})}else{await new Follow({follower:req.userId,following:req.params.id}).save();await User.findByIdAndUpdate(req.params.id,{$inc:{followersCount:1}});await User.findByIdAndUpdate(req.userId,{$inc:{followingCount:1}});const u=await User.findById(req.params.id);if(u&&u.followersCount>=parseInt(process.env.AD_FOLLOWER_THRESHOLD||1000))await User.findByIdAndUpdate(req.params.id,{canShowAds:true});res.json({isFollowing:true})}}catch(e){res.status(500).json({error:'操作失败'})}});

app.get('/api/users/:id',optAuth,async(req,res)=>{try{const user=await User.findById(req.params.id).select('-password -email');if(!user)return res.status(404).json({error:'用户不存在'});let isFollowing=false;if(req.userId&&req.userId!==req.params.id)isFollowing=!!(await Follow.findOne({follower:req.userId,following:req.params.id}));const templates=await Template.find({author:req.params.id,isPublic:true}).sort({likes:-1}).limit(20);res.json({user,templates,isFollowing})}catch(e){res.status(500).json({error:'获取失败'})}});

app.get('/api/stats',auth,async(req,res)=>{try{const user=await User.findById(req.userId);const templates=await Template.find({author:req.userId});res.json({followersCount:user.followersCount,followingCount:user.followingCount,templatesCount:templates.length,totalLikes:templates.reduce((s,t)=>s+t.likes,0),totalUses:templates.reduce((s,t)=>s+t.usageCount,0),canShowAds:user.canShowAds,adRevenue:user.adRevenue,adThreshold:parseInt(process.env.AD_FOLLOWER_THRESHOLD||1000)})}catch(e){res.status(500).json({error:'获取失败'})}});

// ==================== AI 智能写作 ====================
app.post('/api/ai/generate',auth,async(req,res)=>{try{
const{prompt,type}=req.body;
const apiKey=process.env.AI_API_KEY;
const apiUrl=process.env.AI_API_URL||'https://api.deepseek.com/v1/chat/completions';
const model=process.env.AI_MODEL||'deepseek-chat';
if(!apiKey)return res.status(400).json({error:'AI功能未配置，请联系管理员添加 AI_API_KEY'});
if(!prompt)return res.status(400).json({error:'请输入内容'});

const prompts={
  'write':'你是一个专业的公众号文案写作专家。请根据用户给的主题，写一篇高质量的公众号文章。要求：1.标题吸引人 2.内容有深度 3.排版用HTML标签（h1,h2,p,blockquote等）4.字数800-1500字 5.包含小标题分段 6.结尾有总结。直接输出HTML格式的文章内容，不要输出markdown。',
  'polish':'你是一个专业的文案润色专家。请优化以下文字，使其更加流畅、专业、有感染力。保持原意不变，输出优化后的纯文本。',
  'expand':'你是一个专业的内容扩展专家。请将以下内容扩展为更详细、更丰富的段落。增加例子、数据或细节描述。输出扩展后的纯文本。',
  'title':'你是一个爆款标题专家。请根据以下内容，生成5个吸引人的公众号标题。每个标题一行，用数字编号。标题要有吸引力，激发好奇心。',
  'summary':'你是一个内容摘要专家。请将以下内容总结为3-5句话的精华摘要。',
  'outline':'你是一个内容策划专家。请根据以下主题，生成一个详细的文章大纲。包含主标题和3-5个小标题，每个小标题下有2-3个要点。',
  'rewrite':'你是一个文案改写专家。请用不同的表达方式重写以下内容，保持原意但换一种风格。输出改写后的纯文本。',
  'slogan':'你是一个广告文案专家。请根据以下内容，生成5条简短有力的宣传语/金句。每条一行。'
};

const systemPrompt=prompts[type]||prompts['write'];

const response=await fetch(apiUrl,{
  method:'POST',
  headers:{'Content-Type':'application/json','Authorization':'Bearer '+apiKey},
  body:JSON.stringify({model,messages:[{role:'system',content:systemPrompt},{role:'user',content:prompt}],max_tokens:3000,temperature:0.7})
});

if(!response.ok){const err=await response.text();return res.status(500).json({error:'AI服务调用失败：'+response.status})}
const data=await response.json();
const content=data.choices?.[0]?.message?.content||'生成失败，请重试';
res.json({content});
}catch(e){res.status(500).json({error:'AI生成失败：'+e.message})}});

app.get('/api/ai/status',(req,res)=>{res.json({enabled:!!process.env.AI_API_KEY})});

// ==================== 内置模板 ====================
async function seedBuiltinTemplates(){if(await Template.countDocuments({isBuiltin:true})>0)return;let admin=await User.findOne({username:'system'});if(!admin){admin=new User({username:'system',email:'system@editor.com',password:await bcrypt.hash('system_admin_2024',12),role:'admin'});await admin.save()}
const tpls=[
{name:'清新简约',description:'干净清爽，适合日常推文',category:'简约',tags:['简约','清新'],cssContent:`.tpl-body{font-family:'PingFang SC',sans-serif;color:#3e3e3e;line-height:2;padding:20px;background:#fff}.tpl-body h1{font-size:22px;color:#2c3e50;text-align:center;margin:30px 0 20px;font-weight:700;letter-spacing:2px}.tpl-body h2{font-size:18px;color:#1a8f6e;border-left:4px solid #1a8f6e;padding-left:12px;margin:25px 0 15px}.tpl-body p{font-size:15px;margin:12px 0;text-align:justify}.tpl-body blockquote{background:#f7f9fa;border-left:4px solid #1a8f6e;padding:15px 20px;margin:20px 0;border-radius:0 8px 8px 0;font-size:14px;color:#666}.tpl-body .highlight{background:linear-gradient(to bottom,transparent 60%,#a8edca 60%);padding:0 2px}.tpl-body .end-mark{text-align:center;color:#1a8f6e;font-size:20px;margin:30px 0 10px;letter-spacing:5px}`,htmlContent:`<div class="tpl-body"><h1>在这里输入标题</h1><p style="text-align:center;color:#1a8f6e;letter-spacing:10px;font-size:12px">● ● ●</p><p>在这里开始写文章。这是一个<span class="highlight">清新简约</span>风格的模板。</p><h2>小标题一</h2><p>简洁大方的排版让读者更舒适地阅读。</p><blockquote>这里是引用文字，可以强调重要观点。</blockquote><h2>小标题二</h2><p>继续添加你的精彩内容。</p><p class="end-mark">— END —</p></div>`},
{name:'科技深蓝',description:'科技感十足，适合科技类文章',category:'科技',tags:['科技','蓝色'],cssContent:`.tpl-body{font-family:'PingFang SC',sans-serif;color:#e0e6ed;line-height:2;padding:25px;background:linear-gradient(135deg,#0c1b2e,#162d50);border-radius:12px}.tpl-body h1{font-size:24px;text-align:center;margin:25px 0;background:linear-gradient(90deg,#00d2ff,#3a7bd5);-webkit-background-clip:text;-webkit-text-fill-color:transparent;font-weight:800}.tpl-body h2{font-size:18px;color:#00d2ff;padding:8px 15px;border-left:3px solid #00d2ff;background:rgba(0,210,255,0.08);border-radius:0 6px 6px 0;margin:25px 0 15px}.tpl-body p{font-size:15px;margin:12px 0;color:#c4cdd5}.tpl-body blockquote{background:rgba(0,210,255,0.06);border:1px solid rgba(0,210,255,0.2);padding:15px 20px;border-radius:8px;color:#8bb8cc;margin:15px 0}.tpl-body code{background:rgba(0,210,255,0.1);color:#00d2ff;padding:2px 8px;border-radius:4px;font-size:13px}.tpl-body .divider{height:1px;background:linear-gradient(90deg,transparent,#00d2ff,transparent);margin:25px 0}`,htmlContent:`<div class="tpl-body"><h1>🚀 科技资讯标题</h1><div class="divider"></div><p>在这里撰写科技类文章内容。</p><h2>💡 核心亮点</h2><p>使用<code>代码风格</code>突出技术关键词。</p><blockquote>💬 "科技改变世界，创新引领未来。"</blockquote><div class="divider"></div></div>`},
{name:'文艺暖阳',description:'温暖文艺，适合散文、读书笔记',category:'文艺',tags:['文艺','温暖'],cssContent:`.tpl-body{font-family:'Noto Serif SC','STSong',serif;color:#5a4a3a;line-height:2.2;padding:25px;background:#fdf8f0}.tpl-body h1{font-size:24px;text-align:center;color:#8b5e3c;margin:30px 0;font-weight:700;letter-spacing:5px}.tpl-body h2{font-size:18px;color:#8b5e3c;text-align:center;margin:25px 0 15px}.tpl-body p{font-size:15px;margin:15px 0;text-indent:2em;text-align:justify}.tpl-body blockquote{background:#fff7ed;border-left:3px solid #d4a76a;padding:15px 20px;margin:20px 0;font-style:italic;color:#8b7355;border-radius:0 8px 8px 0}.tpl-body .poem{text-align:center;color:#8b5e3c;font-size:16px;line-height:2.5;margin:20px 0;letter-spacing:2px}`,htmlContent:`<div class="tpl-body"><p style="text-align:center;color:#d4a76a;font-size:18px;letter-spacing:8px">🍂 🍂 🍂</p><h1>在这里写下标题</h1><p>在这个温暖的午后，开始写下你的文字。</p><h2>✦ 篇章一 ✦</h2><p>用最温柔的文字，诉说最动人的故事。</p><blockquote>生活不只有眼前的苟且，还有诗和远方。</blockquote><div class="poem">风轻轻吹过<br>带走了昨日的忧愁<br>留下了明日的希望</div></div>`},
{name:'商务精英',description:'专业大气，适合企业宣传',category:'商务',tags:['商务','专业'],cssContent:`.tpl-body{font-family:'PingFang SC',sans-serif;color:#2d3436;line-height:1.9;padding:25px;background:#fff}.tpl-body h1{font-size:24px;text-align:center;color:#1e3a5f;margin:25px 0;font-weight:800;border-bottom:3px solid #1e3a5f;padding-bottom:15px}.tpl-body h2{font-size:17px;color:#fff;background:linear-gradient(135deg,#1e3a5f,#2d5f8a);padding:10px 20px;margin:25px 0 15px;border-radius:4px}.tpl-body p{font-size:14px;margin:10px 0;text-align:justify}.tpl-body blockquote{background:#f8f9fa;border-left:4px solid #1e3a5f;padding:15px;margin:15px 0;font-size:14px;color:#555}.tpl-body .data-box{background:linear-gradient(135deg,#f5f7fa,#e8ecf1);padding:20px;border-radius:8px;margin:15px 0;text-align:center}.tpl-body .data-box .number{font-size:36px;font-weight:800;color:#e74c3c}.tpl-body .data-box .label{font-size:13px;color:#666;margin-top:5px}`,htmlContent:`<div class="tpl-body"><h1>2024 年度行业报告</h1><p style="text-align:center;color:#666;font-size:13px">专业 · 权威 · 深度</p><h2>📊 核心数据概览</h2><div style="display:flex;gap:10px;flex-wrap:wrap"><div class="data-box" style="flex:1;min-width:120px"><div class="number">156%</div><div class="label">同比增长</div></div><div class="data-box" style="flex:1;min-width:120px"><div class="number">2.8亿</div><div class="label">活跃用户</div></div></div><h2>📋 详细分析</h2><p>在这里编写分析内容。</p><blockquote>关键发现：行业正在经历结构性变革。</blockquote></div>`},
{name:'潮流时尚',description:'大胆配色，适合时尚内容',category:'时尚',tags:['时尚','潮流'],cssContent:`.tpl-body{font-family:'PingFang SC',sans-serif;color:#2d3436;line-height:1.9;padding:20px;background:#fff}.tpl-body h1{font-size:28px;text-align:center;margin:20px 0;font-weight:900;background:linear-gradient(135deg,#f093fb,#f5576c,#ffd200);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.tpl-body h2{font-size:18px;color:#fff;display:inline-block;background:linear-gradient(135deg,#f5576c,#f093fb);padding:6px 20px;border-radius:25px;margin:20px 0 15px}.tpl-body .card{background:linear-gradient(135deg,#ffecd2,#fcb69f);padding:20px;border-radius:15px;margin:15px 0;color:#5a3e36}.tpl-body .tag{display:inline-block;background:#f5576c;color:#fff;padding:4px 14px;border-radius:20px;font-size:12px;margin:3px}.tpl-body blockquote{background:linear-gradient(135deg,#a18cd1,#fbc2eb);padding:20px;border:none;border-radius:12px;color:#fff;margin:15px 0;font-weight:600}`,htmlContent:`<div class="tpl-body"><h1>✨ 潮流风向标 ✨</h1><p style="text-align:center"><span class="tag">🔥 HOT</span><span class="tag">💫 TREND</span><span class="tag">⚡ NEW</span></p><h2>🌟 今日潮流</h2><p>这里是你的潮流内容。</p><div class="card"><p style="font-size:18px;font-weight:700;margin:0 0 10px">📸 潮流穿搭分享</p><p style="margin:0">用最in的风格，展示最cool的态度！</p></div><blockquote>💬 生活需要一点色彩！</blockquote></div>`},
{name:'美食诱惑',description:'暖色调美食风格',category:'美食',tags:['美食','餐饮'],cssContent:`.tpl-body{font-family:'PingFang SC',sans-serif;color:#4a3728;line-height:2;padding:20px;background:#fffbf5}.tpl-body h1{font-size:24px;text-align:center;color:#d4451a;margin:25px 0;font-weight:800}.tpl-body h2{font-size:17px;color:#d4451a;margin:20px 0 10px;text-align:center}.tpl-body .food-card{background:#fff;border-radius:12px;padding:15px;margin:15px 0;box-shadow:0 3px 15px rgba(212,69,26,0.1)}.tpl-body .food-card .name{font-size:18px;font-weight:700;color:#d4451a}.tpl-body .rating{color:#ffa502;font-size:16px}.tpl-body blockquote{background:#fff3e6;border-left:4px solid #ffa502;padding:15px;margin:15px 0;border-radius:0 8px 8px 0;color:#8b6914}`,htmlContent:`<div class="tpl-body"><h1>🔥 美食探店指南</h1><p style="text-align:center;font-size:18px;letter-spacing:5px">🍕 🍜 🍰 🍣</p><p>今天带大家探索一家宝藏美食店！</p><h2>🍽️ 招牌推荐 🍽️</h2><div class="food-card"><div class="name">🥘 秘制红烧肉</div><div class="rating">★★★★★</div><p>入口即化，肥而不腻</p></div><div class="food-card"><div class="name">🍜 手工拉面</div><div class="rating">★★★★☆</div><p>汤底浓郁，面条劲道</p></div><blockquote>🗣️ "这是我吃过最好吃的一家店！"</blockquote></div>`},
{name:'教育知识',description:'清晰易读，适合知识分享',category:'教育',tags:['教育','知识'],cssContent:`.tpl-body{font-family:'PingFang SC',sans-serif;color:#333;line-height:2;padding:20px;background:#f0f5ff}.tpl-body h1{font-size:22px;text-align:center;color:#2b4acb;margin:25px 0;font-weight:700}.tpl-body h2{font-size:17px;color:#2b4acb;padding:8px 15px;background:#e6edff;border-radius:6px;margin:20px 0 12px}.tpl-body .tip-box{background:#fff;border:1px solid #d4e0ff;border-radius:10px;padding:15px;margin:15px 0}.tpl-body .tip-box .tip-title{color:#2b4acb;font-weight:700;font-size:14px;margin-bottom:8px}.tpl-body .step{display:flex;align-items:flex-start;gap:12px;margin:12px 0}.tpl-body .step-num{min-width:28px;height:28px;background:#2b4acb;color:#fff;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:700}.tpl-body blockquote{background:#e6edff;border-left:4px solid #2b4acb;padding:12px 18px;margin:15px 0;border-radius:0 8px 8px 0;font-size:14px;color:#555}`,htmlContent:`<div class="tpl-body"><h1>📚 知识分享标题</h1><p style="text-align:center;color:#888;font-size:13px">3分钟学会 · 简单易懂</p><h2>📖 知识要点</h2><p>这是一个教育类模板。</p><div class="tip-box"><div class="tip-title">💡 重点提示</div><p style="margin:0;font-size:14px">这里放置需要注意的要点。</p></div><h2>📝 操作步骤</h2><div class="step"><div class="step-num">1</div><div>第一步：描述操作</div></div><div class="step"><div class="step-num">2</div><div>第二步：继续操作</div></div><div class="step"><div class="step-num">3</div><div>第三步：完成</div></div><blockquote>学习是一个循序渐进的过程！</blockquote></div>`},
{name:'极简黑金',description:'高端大气的黑金配色',category:'时尚',tags:['高端','黑金'],cssContent:`.tpl-body{font-family:'PingFang SC',sans-serif;color:#d4c5a0;line-height:2;padding:30px;background:#0a0a0a}.tpl-body h1{font-size:26px;text-align:center;color:#c9a96e;margin:30px 0;font-weight:300;letter-spacing:8px}.tpl-body h2{font-size:16px;color:#c9a96e;text-align:center;margin:25px 0 15px;letter-spacing:5px;font-weight:300}.tpl-body p{font-size:14px;margin:12px 0;color:#999;letter-spacing:1px}.tpl-body blockquote{border:1px solid #c9a96e;padding:20px;margin:20px 0;text-align:center;color:#c9a96e;font-size:16px;letter-spacing:3px;background:transparent}.tpl-body .gold-line{height:1px;background:linear-gradient(90deg,transparent,#c9a96e,transparent);margin:30px 0}`,htmlContent:`<div class="tpl-body"><div class="gold-line"></div><h1>品牌名称</h1><p style="text-align:center;color:#666;font-size:12px;letter-spacing:5px">ELEGANCE · LUXURY · TIMELESS</p><div class="gold-line"></div><h2>—— 臻选系列 ——</h2><p>以匠心精神，打造每一件作品。</p><blockquote>「 极致，源于对细节的执着 」</blockquote><div class="gold-line"></div></div>`}
];
for(const t of tpls)await new Template({...t,author:admin._id,isBuiltin:true,isPublic:true}).save();console.log('✅ 内置模板初始化完成')}

const PORT=process.env.PORT||3000;
mongoose.connect(process.env.MONGODB_URI).then(async()=>{console.log('✅ MongoDB 连接成功');await seedBuiltinTemplates();app.listen(PORT,()=>console.log('🚀 服务器运行在端口 '+PORT))}).catch(err=>{console.error('❌ MongoDB 连接失败:',err.message);process.exit(1)});
app.get('*',(req,res)=>{if(!req.path.startsWith('/api')&&!req.path.startsWith('/uploads'))res.sendFile(path.join(__dirname,'public','index.html'))});
